[package]
name = "md-icons-helper"
version = "0.1.0"
edition = "2021"
description = "Helper library for md-icons"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
proc-macro = true
